import ts, { Identifier } from "typescript";

export const beforeEach: Identifier = ts.createIdentifier("beforeEach");
export const async: Identifier = ts.createIdentifier('async');
export const masterServiceStub: Identifier = ts.createIdentifier('masterServiceStub');
export const MasterServiceStub: Identifier = ts.createIdentifier('MasterServiceStub');
export const provide: Identifier = ts.createIdentifier('provide');
export const useClass: Identifier = ts.createIdentifier('useClass');
export const declarations: Identifier = ts.createIdentifier('declarations');
export const testBed: Identifier = ts.createIdentifier('TestBed');
export const compileComponents: Identifier = ts.createIdentifier('compileComponents');
export const providers: Identifier = ts.createIdentifier('providers');
export const configureTestingModule: Identifier = ts.createIdentifier('configureTestingModule');
export const describe: Identifier = ts.createIdentifier('describe');
export const component: Identifier = ts.createIdentifier('component');
export const fixture: Identifier = ts.createIdentifier('fixture');
export const createComponent: Identifier = ts.createIdentifier('createComponent');
export const componentInstance: Identifier = ts.createIdentifier('componentInstance');
export const service: Identifier = ts.createIdentifier('service');
export const get: Identifier = ts.createIdentifier('get');
export const componentFixture: Identifier = ts.createIdentifier('ComponentFixture');